name: Setup

runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.8'
      cache: 'pip'
  - run: |
      set -e
      pip install -r requirements.txt
      pip install -r tests/requirements.txt
      pip install -r docs/requirements.txt
      pip install .
    shell: bash
