name: Setup

runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.8'
      cache: 'pip'
  - run: pip install -r requirements.txt
  - run: pip install -r tests/requirements.txt
  - run: pip install -r docs/requirements.txt
  - run: pip install .
