name: flake8 Lint

on: [pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: py-actions/flake8@v2.3.0
        with:
          path: "src tests"
