name: publish docs

on:
  push:
    branches:
    - main
    paths:
    - '*.md'
    - '.github/**'
    - 'INSTALL'
    - 'LICENSE'
    - 'assets/**'
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-pkg
    - uses: ./.github/actions/render-docs
    - name: Set GH-Pages domain name
      run: echo 'validate-docs.phes-odm.org' > ${{ github.workspace }}/CNAME
    - name: Commit CNAME file
      run: |
        git add CNAME
        git commit -m "Add CNAME"
    - name: Push to GitHub Pages
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
