name: Generate docs and push to Github Pages
on:
  push:
    branches:
    - main
    paths:
    - '.github/**'
    - 'assets/**'
    - 'docs/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: nikeee/setup-pandoc@v1
    - uses: quarto-dev/quarto-actions/setup@v2.0.3
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
    - name: Render Quarto docs
      run: python tools/render_quarto_docs.py
    - name: Set GH-Pages domain name
      run: echo 'validate-docs.phes-odm.org' > CNAME
    - name: Build and Commit
      uses: sphinx-notes/pages@3 # requires checkout with `fetch-depth: 0`
      with:
        documentation_path: docs
        target_branch: gh-pages
    - name: Push to GitHub Pages
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
