name: Test generated assets

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: test-gen-assets
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: pip install -e .
    - run: python src/odm_validation/tools/generate_assets.py
    - name: Detect changed files
      run: |
        # Fetch all files and ensure the working directory is clean
        git fetch --all

        # Check for uncommitted changes
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "\nERROR: There are uncommitted or changed files in the repository."
          echo "\nPlease commit or stash the changes before pushing."
          git status
          exit 1
        fi

        echo "No changed files detected. Repository is clean."
