name: test doc generation

on:
  pull_request:
    paths:
    - '*.md'
    - '.github/**'
    - 'INSTALL'
    - 'LICENSE'
    - 'assets/**'
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-pkg
    - uses: ./.github/actions/render-docs
