name: Test documentation generation

on:
  pull_request:
    paths:
    - '*.md'
    - '.github/**'
    - 'INSTALL'
    - 'LICENSE'
    - 'assets/**'
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: nikeee/setup-pandoc@v1
    - uses: quarto-dev/quarto-actions/setup@v2.0.3
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
        pip install -r docs/requirements.txt
        pip install .
    - name: Render Quarto docs
      run: python src/odm_validation/tools/render_quarto_docs.py
    - name: Build and Commit
      uses: sphinx-notes/pages@2.1 # requires checkout with `fetch-depth: 0`
      with:
        documentation_path: docs
        target_branch: gh-pages
